config/routes.rb
Rails.application.routes.draw do
  root :to => 'stories#index'
  resources :stories do
    resources :sentences
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flikr.rb
class Flickr
  include HTTParty

  base_uri 'api.flickr.com'

  def self.getPhotos()
    return get('/services/rest/', :query => {
      :method => 'flickr.photos.getPopular',
      :api_key => '02d6e7ae3a37fd5bf6c6c553ec18956d'
      })
  end
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  belongs_to :story
  validates :author, :presence => true
  validates :text, :presence => true
  before_save :check_for_period

  private
    def check_for_period
      if self.text[-1] == "."
        self.text = self.text[0..-2]
      end
    end
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :sentences
  validates :name, :presence => true

  scope :most_sentences, -> {(
    select("stories.id, stories.name, stories.image, count(sentences.id) as sentences_count")
    .joins(:sentences)
    .group("stories.id")
    .order("sentences_count DESC")
    .limit(1)
    )}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController

  def index

  end

  def new
    @story = Story.find(params[:story_id])
    @sentence = @story.sentences.new
    @sentences = @story.sentences
  end

  def create
    @story = Story.find(params[:story_id])
    @sentence = @story.sentences.new(sentence_params)
    if @sentence.save
      flash[:notice] = "Sentence added."
      redirect_to story_path(@story)
    else
      render :new
    end
  end


  def edit
    @story = Story.find(params[:story_id])
    @sentence = Sentence.find(params[:id])
  end

  def update
    @story = Story.find(params[:story_id])
    @sentence = Sentence.find(params[:id])
    if @sentence.update(sentence_params)
      redirect_to story_path(@sentence.story)
    else
      render :edit
    end
  end

  def destroy
    @sentence = Sentence.find(params[:id])
    @sentence.destroy
    redirect_to story_path(@sentence.story)
  end



private
  def sentence_params
    params.require(:sentence).permit(:author, :text)
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all
    render :index
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    # @story.image = "#{rand(1..3)}.jpg"
    if @story.save
      flash[:notice] = "New story created."
      redirect_to story_path(@story)
    else
      render :new
    end
  end

  def show
    @story = Story.find(params[:id])
    @sentences = @story.sentences
  end

  def edit
    @story = Story.find(params[:id])
    @sentences = @story.sentences
  end

  def update
    @story = Story.find(params[:id])
    @sentences = @story.sentences
    if @story.update(story_params)
      redirect_to story_path(@story)
    else
      render :edit
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to stories_path
  end

private
  def story_params
    params.require(:story).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryTime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sentences/_form.html.erb
<%= form_for [@story, @sentence] do |f| %>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_field :text, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/sentences/edit.html.erb
<h1>Edit <%= @sentence.text %></h1>

<%= render "form" %>

app/views/sentences/new.html.erb
<div id="story">
  <h1><%= @story.name %></h1>
  <%= image_tag(@story.image, class: 'story-image') %>
  <div id="sentences">
    <% @sentences.each_with_index do |sentence, index| %>
      <% unless index == @sentences.length - 1 %>
        <div class="sentence-box">
          <div class="sentence-tab">
            <%= sentence.author %>
          </div>
          <div class="sentence"><%= sentence.text %></div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= render 'layouts/errors', :object => @sentence %>
  <%= render 'form' %>
  <%= link_to "Back", story_path(@story), class: "btn btn-danger" %>
</div>

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/stories/edit.html.erb
<div id="story">
  <h1><%= @story.name %></h1>
  <%= image_tag(@story.image, class: 'story-image') %>
  <% @sentences.each do |sentence| %>
    <div class="sentence-box">
      <div class="sentence-tab">
        <%= sentence.author %>
      </div>
      <div class="sentence"><%= sentence.text %></div>
    </div>
  <% end %>
  <div id="buttons">
    <%= link_to "Add Sentence", new_story_sentence_path(@story), class: "btn btn-info" %>
    <%= link_to "Edit this Story", edit_story_path(@story), class: "btn btn-warning" %>
    <%= link_to "Delete this Story", story_path(@story),
    :data => { :confirm => "Are you sure you want to delete this story?",
      :method => "delete"}, class: "btn btn-danger" %>
  </div>
</div>

<h3>Edit <%= @story.name %></h3>
<%= render "form" %>

app/views/stories/index.html.erb
<h1>Stories</h1>
<h2>Featured Story</h2>
<%= link_to Story.most_sentences.first.name, story_path(Story.most_sentences.first) %>
<ul>
  <% @stories.each do |story| %>
  <li class="story-list"><%= link_to story.name, story_path(story) %></li>
  <% end %>
</ul>
<br>
<%= link_to "New Story", new_story_path, class: "btn btn-primary" %>

app/views/stories/new.html.erb
<h1>New Story</h1>
<%= render 'layouts/errors', :object => @story %>
<%= render 'form' %>
<br>
<%= link_to "Back", stories_path, class: "btn btn-info" %>

app/views/stories/show.html.erb
<div id="story">
  <%= flash[:notice] %>
  <h1><%= @story.name %></h1>
  <%= image_tag(@story.image, class: 'story-image') %>
  <% @sentences.each do |sentence| %>
    <div class="sentence-box">
      <div class="sentence-tab">
        <%= sentence.author %>
      </div>
      <div class="sentence"><%= sentence.text %></div>
    </div>
  <% end %>
  <div id="buttons">
    <%= link_to "Add Sentence", new_story_sentence_path(@story), class: "btn btn-info" %>
    <%= link_to "Edit this Story", edit_story_path(@story), class: "btn btn-warning" %>
    <%= link_to "Delete this Story", story_path(@story),
    :data => { :confirm => "Are you sure you want to delete this story?",
      :method => "delete"}, class: "btn btn-danger" %>
    <%= link_to "All Stories", stories_path, class: "btn btn-info" %>
  </div>
</div>